version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: ./src/app/Dockerfile
      target: devcontainer
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  app:
    build:
      context: ./src/app
      target: runner
    container_name: app_service
    restart: never
    # ports:
    #   - '8000:8000'
