---
name: Tox

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  #   paths-ignore:
  #     - "docs/**"
  #     - "mypyc/doc/**"
  #     - "**/*.rst"
  #     - "**/*.md"
  #     - .gitignore
  #     - CREDITS
  #     - LICENSE
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        include:
          - name: Test suite with py38-ubuntu
            python: "3.8"
            arch: x64
            os: ubuntu-latest
            toxenv: py
            tox_extra_args: "-n 2"
          - name: Test suite with py39-ubuntu
            python: "3.9"
            arch: x64
            os: ubuntu-latest
            toxenv: py
            tox_extra_args: "-n 2"
          - name: Test suite with py310-ubuntu
            python: "3.10"
            arch: x64
            os: ubuntu-latest
            toxenv: py
            tox_extra_args: "-n 2"
          - name: Test suite with py311-ubuntu
            python: "3.11"
            arch: x64
            os: ubuntu-latest
            toxenv: py
            tox_extra_args: "-n 2"
          - name: Test suite with py312-ubuntu
            python: "3.12"
            arch: x64
            os: ubuntu-latest
            toxenv: py
            tox_extra_args: "-n 2"
    name: ${{ matrix.name }}
    env:
      TOX_SKIP_MISSING_INTERPRETERS: False
      # Rich (pip)
      FORCE_COLOR: 1
      # Tox
      PY_COLORS: 1
      # Mypy (see https://github.com/python/mypy/issues/7771)
      TERM: xterm-color
      MYPY_FORCE_COLOR: 1
      MYPY_FORCE_TERMINAL_WIDTH: 200
      # Pytest
      PYTEST_ADDOPTS: --color=yes
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
      - name: Install tox
        run: pip install setuptools==68.2.2 tox==4.11.0
      - name: Setup tox environment
        run: tox run -e ${{ matrix.toxenv }} --notest
      - name: Test
        run: tox run -e ${{ matrix.toxenv }} --skip-pkg-install -- ${{ matrix.tox_extra_args }}
